# Data Cube OLAP
* Nama: Muhammad Rifat Bagus Adikusuma
* NIM: 20/456371/TK/50501
* Prodi : Teknologi Informasi

In [ ]:
import numpy as np
import pandas as pd
import atoti as tt
from treelib import Node, Tree


In [2]:
# Load DataSet
assess = pd.read_csv('assessments.csv')
courses = pd.read_csv('courses.csv')
studentassess = pd.read_csv('studentAssessment.csv')
studentInfo = pd.read_csv('studentInfo.csv')
studentReg = pd.read_csv('studentRegistration.csv')
studentVle =pd.read_csv('studentVle.csv',)
vle = pd.read_csv('vle.csv')

# Data Cleaning

## Assessment

In [3]:
assess.head(10)

code_module code_presentation  id_assessment assessment_type   date  weight
0         AAA             2013J           1752             TMA   19.0    10.0
1         AAA             2013J           1753             TMA   54.0    20.0
2         AAA             2013J           1754             TMA  117.0    20.0
3         AAA             2013J           1755             TMA  166.0    20.0
4         AAA             2013J           1756             TMA  215.0    30.0
5         AAA             2013J           1757            Exam    NaN   100.0
6         AAA             2014J           1758             TMA   19.0    10.0
7         AAA             2014J           1759             TMA   54.0    20.0
8         AAA             2014J           1760             TMA  117.0    20.0
9         AAA             2014J           1761             TMA  166.0    20.0

### Cek Missing Value and Duplicate Rows

In [4]:

null_value = pd.DataFrame(assess.isnull().sum().sort_values(ascending=False)).reset_index()
null_value.columns = ['Column','Null Values']
null_value

Column  Null Values
0               date           11
1        code_module            0
2  code_presentation            0
3      id_assessment            0
4    assessment_type            0
5             weight            0

In [5]:
assess[assess.duplicated()]

Empty DataFrame
Columns: [code_module, code_presentation, id_assessment, assessment_type, date, weight]
Index: []

In [6]:
len(assess)-len(assess.drop_duplicates())

0

In [7]:
assess\
.groupby(['code_module','code_presentation'])\
.agg(total_weight = ('weight',sum))

total_weight
code_module code_presentation              
AAA         2013J                     200.0
            2014J                     200.0
BBB         2013B                     200.0
            2013J                     200.0
            2014B                     200.0
            2014J                     200.0
CCC         2014B                     300.0
            2014J                     300.0
DDD         2013B                     200.0
            2013J                     200.0
            2014B                     200.0
            2014J                     200.0
EEE         2013J                     200.0
            2014B                     200.0
            2014J                     200.0
FFF         2013B                     200.0
            2013J                     200.0
            2014B                     200.0
            2014J                     200.0
GGG         2013J                     100.0
            2014B                     100.0
            2014J                     100.0

Pada deskripsi data dikatakan bahwa sum dari assessment selain exam adalah 100. Dimana exam diperlakukan terpisah dengan weight 100%. Maka jika melihat data diatas assessment yang memiliki nilai diatas 100 memiliki weight tambahan yang berasal dari exams


In [8]:
assess[assess['assessment_type'] == 'Exam']\
.groupby(['code_module','code_presentation','assessment_type'])\
.agg(total_weight = ('weight',sum))

total_weight
code_module code_presentation assessment_type              
AAA         2013J             Exam                    100.0
            2014J             Exam                    100.0
BBB         2013B             Exam                    100.0
            2013J             Exam                    100.0
            2014B             Exam                    100.0
            2014J             Exam                    100.0
CCC         2014B             Exam                    200.0
            2014J             Exam                    200.0
DDD         2013B             Exam                    100.0
            2013J             Exam                    100.0
            2014B             Exam                    100.0
            2014J             Exam                    100.0
EEE         2013J             Exam                    100.0
            2014B             Exam                    100.0
            2014J             Exam                    100.0
FFF         2013B             Exam                    100.0
            2013J             Exam                    100.0
            2014B             Exam                    100.0
            2014J             Exam                    100.0
GGG         2013J             Exam                    100.0
            2014B             Exam                    100.0
            2014J             Exam                    100.0

In [9]:
assess\
.groupby(['code_module','code_presentation', 'assessment_type'])\
.agg(weight_by_type = ('weight',sum))

weight_by_type
code_module code_presentation assessment_type                
AAA         2013J             Exam                      100.0
                              TMA                       100.0
            2014J             Exam                      100.0
                              TMA                       100.0
BBB         2013B             CMA                         5.0
                              Exam                      100.0
                              TMA                        95.0
            2013J             CMA                         5.0
                              Exam                      100.0
                              TMA                        95.0
            2014B             CMA                         5.0
                              Exam                      100.0
                              TMA                        95.0
            2014J             Exam                      100.0
                              TMA                       100.0
CCC         2014B             CMA                        25.0
                              Exam                      200.0
                              TMA                        75.0
            2014J             CMA                        25.0
                              Exam                      200.0
                              TMA                        75.0
DDD         2013B             CMA                        25.0
                              Exam                      100.0
                              TMA                        75.0
            2013J             Exam                      100.0
                              TMA                       100.0
            2014B             Exam                      100.0
                              TMA                       100.0
            2014J             Exam                      100.0
                              TMA                       100.0
EEE         2013J             Exam                      100.0
                              TMA                       100.0
            2014B             Exam                      100.0
                              TMA                       100.0
            2014J             Exam                      100.0
                              TMA                       100.0
FFF         2013B             CMA                         0.0
                              Exam                      100.0
                              TMA                       100.0
            2013J             CMA                         0.0
                              Exam                      100.0
                              TMA                       100.0
            2014B             CMA                         0.0
                              Exam                      100.0
                              TMA                       100.0
            2014J             CMA                         0.0
                              Exam                      100.0
                              TMA                       100.0
GGG         2013J             CMA                         0.0
                              Exam                      100.0
                              TMA                         0.0
            2014B             CMA                         0.0
                              Exam                      100.0
                              TMA                         0.0
            2014J             CMA                         0.0
                              Exam                      100.0
                              TMA                         0.0

### Mencocokkan Assessment info dengan Assessment pada Student Assessment

In [10]:
## Mencari dan membandingkan kolom pada tabel
def compareCols(df1, df2):
    # (a) Make lists of columns for each data frame
    df1Columns = df1.columns.values.tolist()
    df2Columns = df2.columns.values.tolist()

    # (b) Find column names that are the same
    diffDict = set(df1Columns) & set(df2Columns)
    
    print('Shared columns : ', diffDict, '\n')

    # (c) Make a list of the dictinary
    diffList = list(diffDict)
    # (d) Check that if values in
    # every shared column match in
    # the two dataframes
    for col in diffList:
        x = df1[col].isin(df2[col]).value_counts()
        print('Check if values are present in both dataframes:')
        print(x, '\n')
        

compareCols(assess, studentassess)

Shared columns :  {'id_assessment'} 

Check if values are present in both dataframes:
True     188
False     18
Name: id_assessment, dtype: int64 



In [11]:
## Mencari different Value
def findDiffValues(df1, df2, col):
    '''
    Find all df1.col values not present in df2.col
    '''
    # Pull out all unique values of col
    df1_IDs = df1[col].unique()
    df2_IDs = df2[col].unique()

    # Compare the two lists
    # (a) Find what values are different
    diff = set(df1_IDs).difference(set(df2_IDs))
    # (b) Count how many are different
    numberDiff = len(diff)

    print("Values from df1 not in df2: " + str(diff))
    print("Number of missing values: " + str(numberDiff))

findDiffValues(assess, studentassess, 'id_assessment')

Values from df1 not in df2: {30723, 1763, 34885, 15014, 37444, 14990, 30713, 37424, 15025, 34898, 37434, 40087, 34872, 40088, 15002, 1757, 30718, 34911}
Number of missing values: 18


In [12]:
def printDiffValues(df1, df2, col):
    '''
    Show all df1.col values not present in df2.col
    '''
    # Pull out all unique values id_assessments
    df1_IDs = df1[col].unique()
    df2_IDs = df2[col].unique()

    # Compare the two lists
    # (a) Find what values are different
    diff = set(df1_IDs).difference(set(df2_IDs))
    
    # Show information for all df1.col values not presentin df2.col
    # (a) Make a list of missing values
    missingList = list(diff)
    # (b) Find these IDs in df2
    missingDf = df1[df1[col].isin(missingList)]

    return missingDf


In [13]:
assess.nunique()

code_module            7
code_presentation      4
id_assessment        206
assessment_type        3
date                  74
weight                24
dtype: int64

## Student Assessment

In [14]:
studentassess.head()

id_assessment  id_student  date_submitted  is_banked  score
0           1752       11391              18          0   78.0
1           1752       28400              22          0   70.0
2           1752       31604              17          0   72.0
3           1752       32885              26          0   69.0
4           1752       38053              19          0   79.0

In [15]:
studentassess.isnull().sum()

id_assessment       0
id_student          0
date_submitted      0
is_banked           0
score             173
dtype: int64

In [16]:
studentassess.nunique()

id_assessment       188
id_student        23369
date_submitted      312
is_banked             2
score               101
dtype: int64

In [17]:
studentassess.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173912 entries, 0 to 173911
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   id_assessment   173912 non-null  int64  
 1   id_student      173912 non-null  int64  
 2   date_submitted  173912 non-null  int64  
 3   is_banked       173912 non-null  int64  
 4   score           173739 non-null  float64
dtypes: float64(1), int64(4)
memory usage: 6.6 MB


In [18]:
studentassess[studentassess['score'].isnull()]

id_assessment  id_student  date_submitted  is_banked  score
215              1752      721259              22          0    NaN
937              1754      260355             127          0    NaN
2364             1760     2606802             180          0    NaN
3358            14984      186780              77          0    NaN
3914            14984      531205              26          0    NaN
...               ...         ...             ...        ...    ...
148929          34903      582670             241          0    NaN
159251          37415      610738              87          0    NaN
166390          37427      631786             221          0    NaN
169725          37435      648110              62          0    NaN
170103          37435      480914              49          0    NaN

[173 rows x 5 columns]

Nilai yang kosong dapat diasumsikan bahwa student tersebut tidak mengumpulkan assessment. Sehingga nilai yang kosong dapat di replace dengan nilai 0. 

In [19]:
studentassess.fillna(0, inplace=True)

In [20]:
studentassess[studentassess['score'].isnull()]

Empty DataFrame
Columns: [id_assessment, id_student, date_submitted, is_banked, score]
Index: []

## Student Registration 

In [21]:
studentReg.head()

code_module code_presentation  id_student  date_registration  \
0         AAA             2013J       11391             -159.0   
1         AAA             2013J       28400              -53.0   
2         AAA             2013J       30268              -92.0   
3         AAA             2013J       31604              -52.0   
4         AAA             2013J       32885             -176.0   

   date_unregistration  
0                  NaN  
1                  NaN  
2                 12.0  
3                  NaN  
4                  NaN

In [22]:
studentReg[studentReg.duplicated()]

Empty DataFrame
Columns: [code_module, code_presentation, id_student, date_registration, date_unregistration]
Index: []

In [23]:
null_value = pd.DataFrame(studentReg.isnull().sum().sort_values(ascending=False)).reset_index()
null_value.columns = ['Column','Null Values']
null_value

Column  Null Values
0  date_unregistration        22521
1    date_registration           45
2          code_module            0
3    code_presentation            0
4           id_student            0

In [24]:
compareCols(studentReg, studentassess)

Shared columns :  {'id_student'} 

Check if values are present in both dataframes:
True     26746
False     5847
Name: id_student, dtype: int64 



Terdapat 5847 student yang terdaftar namun tidak memiliki informasi assessment apapun.


In [25]:
compareCols(studentInfo, studentassess)

Shared columns :  {'id_student'} 

Check if values are present in both dataframes:
True     26746
False     5847
Name: id_student, dtype: int64 



Check apakah student tersebut merupakan orang yang sama

In [26]:
# Pull out all unique values id_assessments
studassess_IDs = studentReg['id_student'].unique()
studinfo_IDs = studentInfo['id_student'].unique()

# Compare the two lists
# (a) Find what assessment IDs are different
diff = set(studassess_IDs).difference(set(studinfo_IDs))
# (b) Count how many are different
numberDiff = len(diff)

numberDiff

0

In [27]:
compareCols(studentReg,studentInfo)

Shared columns :  {'id_student', 'code_module', 'code_presentation'} 

Check if values are present in both dataframes:
True    32593
Name: id_student, dtype: int64 

Check if values are present in both dataframes:
True    32593
Name: code_module, dtype: int64 

Check if values are present in both dataframes:
True    32593
Name: code_presentation, dtype: int64 



In [28]:
info_not_in_results = printDiffValues(studentInfo, studentassess, 'id_student')
info_not_in_results.head(10)

code_module code_presentation  id_student gender                region  \
2           AAA             2013J       30268      F  North Western Region   
44          AAA             2013J      135335      F   East Anglian Region   
118         AAA             2013J      281589      M  North Western Region   
125         AAA             2013J      292923      F     South East Region   
136         AAA             2013J      305539      F                 Wales   
169         AAA             2013J      346843      F              Scotland   
171         AAA             2013J      354858      M          South Region   
198         AAA             2013J      405961      M              Scotland   
209         AAA             2013J      494424      F          North Region   
256         AAA             2013J     1763015      F              Scotland   

         highest_education imd_band age_band  num_of_prev_attempts  \
2    A Level or Equivalent   30-40%    35-55                     0   
44      Lower Than A Level   20-30%     0-35                     0   
118       HE Qualification   30-40%     0-35                     0   
125  A Level or Equivalent  90-100%    35-55                     0   
136     Lower Than A Level   80-90%     0-35                     0   
169       HE Qualification   50-60%    35-55                     0   
171       HE Qualification  90-100%    35-55                     0   
198  A Level or Equivalent  90-100%     0-35                     0   
209  A Level or Equivalent   80-90%     0-35                     0   
256  A Level or Equivalent    10-20    35-55                     0   

     studied_credits disability final_result  
2                 60          Y    Withdrawn  
44               180          N    Withdrawn  
118               60          N         Fail  
125              180          N    Withdrawn  
136              120          N    Withdrawn  
169              120          N         Fail  
171              120          N    Withdrawn  
198              240          Y    Withdrawn  
209               60          N         Fail  
256               60          N    Withdrawn

In [29]:
info_not_in_results[info_not_in_results.duplicated()]

Empty DataFrame
Columns: [code_module, code_presentation, id_student, gender, region, highest_education, imd_band, age_band, num_of_prev_attempts, studied_credits, disability, final_result]
Index: []

## Student Informations

In [30]:
studentInfo.isnull().sum()

code_module                0
code_presentation          0
id_student                 0
gender                     0
region                     0
highest_education          0
imd_band                1111
age_band                   0
num_of_prev_attempts       0
studied_credits            0
disability                 0
final_result               0
dtype: int64

In [31]:
studentInfo[studentInfo.duplicated()]

Empty DataFrame
Columns: [code_module, code_presentation, id_student, gender, region, highest_education, imd_band, age_band, num_of_prev_attempts, studied_credits, disability, final_result]
Index: []

In [32]:
studentInfo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32593 entries, 0 to 32592
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   code_module           32593 non-null  object
 1   code_presentation     32593 non-null  object
 2   id_student            32593 non-null  int64 
 3   gender                32593 non-null  object
 4   region                32593 non-null  object
 5   highest_education     32593 non-null  object
 6   imd_band              31482 non-null  object
 7   age_band              32593 non-null  object
 8   num_of_prev_attempts  32593 non-null  int64 
 9   studied_credits       32593 non-null  int64 
 10  disability            32593 non-null  object
 11  final_result          32593 non-null  object
dtypes: int64(3), object(9)
memory usage: 3.0+ MB


### Melihat data yang mungkin untuk digeneralisasi


In [33]:
studentInfo.nunique()

code_module                 7
code_presentation           4
id_student              28785
gender                      2
region                     13
highest_education           5
imd_band                   10
age_band                    3
num_of_prev_attempts        7
studied_credits            61
disability                  2
final_result                4
dtype: int64

In [34]:
print(studentInfo['region'].unique())

['East Anglian Region' 'Scotland' 'North Western Region'
 'South East Region' 'West Midlands Region' 'Wales' 'North Region'
 'South Region' 'Ireland' 'South West Region' 'East Midlands Region'
 'Yorkshire Region' 'London Region']


In [35]:
print(studentInfo['imd_band'].unique())


['90-100%' '20-30%' '30-40%' '50-60%' '80-90%' '70-80%' nan '60-70%'
 '40-50%' '10-20' '0-10%']


### Generalisasi nilai imd_band

In [36]:
def categorise(row):  
    if row['imd_band'] == '0-10%' or row['imd_band']=='10-20' or row['imd_band'] == '20-30%':
        return 'Most Deprived'
    elif row['imd_band'] == '30-40%' or row['imd_band']=='40-50%' or row['imd_band'] == '50-60%' or row['imd_band'] == '60-70%':
        return 'Medium Deprived'
    elif  row['imd_band']=='70-80%' or row['imd_band'] == '80-90%' or  row['imd_band'] == '90-100%':
        return 'Least Deprived'
    return 'nan'

In [37]:
studentInfo['imd_band_Categorize'] = studentInfo.apply(lambda row: categorise(row), axis=1)

In [38]:
studentInfo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32593 entries, 0 to 32592
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   code_module           32593 non-null  object
 1   code_presentation     32593 non-null  object
 2   id_student            32593 non-null  int64 
 3   gender                32593 non-null  object
 4   region                32593 non-null  object
 5   highest_education     32593 non-null  object
 6   imd_band              31482 non-null  object
 7   age_band              32593 non-null  object
 8   num_of_prev_attempts  32593 non-null  int64 
 9   studied_credits       32593 non-null  int64 
 10  disability            32593 non-null  object
 11  final_result          32593 non-null  object
 12  imd_band_Categorize   32593 non-null  object
dtypes: int64(3), object(10)
memory usage: 3.2+ MB


## VLE 

In [39]:
vle.head(10)

id_site code_module code_presentation activity_type  week_from  week_to
0   546943         AAA             2013J      resource        NaN      NaN
1   546712         AAA             2013J     oucontent        NaN      NaN
2   546998         AAA             2013J      resource        NaN      NaN
3   546888         AAA             2013J           url        NaN      NaN
4   547035         AAA             2013J      resource        NaN      NaN
5   546614         AAA             2013J      homepage        NaN      NaN
6   546897         AAA             2013J           url        NaN      NaN
7   546678         AAA             2013J     oucontent        NaN      NaN
8   546933         AAA             2013J      resource        NaN      NaN
9   546708         AAA             2013J     oucontent        NaN      NaN

In [40]:
vle.nunique()

id_site              6364
code_module             7
code_presentation       4
activity_type          20
week_from              30
week_to                30
dtype: int64

In [41]:
vle.isnull().sum()

id_site                 0
code_module             0
code_presentation       0
activity_type           0
week_from            5243
week_to              5243
dtype: int64

In [42]:
vle[vle.duplicated()]

Empty DataFrame
Columns: [id_site, code_module, code_presentation, activity_type, week_from, week_to]
Index: []

In [43]:
vle =vle.drop(['week_from','week_to'],axis=1)

In [44]:
vle.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6364 entries, 0 to 6363
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   id_site            6364 non-null   int64 
 1   code_module        6364 non-null   object
 2   code_presentation  6364 non-null   object
 3   activity_type      6364 non-null   object
dtypes: int64(1), object(3)
memory usage: 199.0+ KB


## StudentVle

In [45]:
studentVle.head(10)

code_module code_presentation  id_student  id_site  date  sum_click
0         AAA             2013J       28400   546652   -10          4
1         AAA             2013J       28400   546652   -10          1
2         AAA             2013J       28400   546652   -10          1
3         AAA             2013J       28400   546614   -10         11
4         AAA             2013J       28400   546714   -10          1
5         AAA             2013J       28400   546652   -10          8
6         AAA             2013J       28400   546876   -10          2
7         AAA             2013J       28400   546688   -10         15
8         AAA             2013J       28400   546662   -10         17
9         AAA             2013J       28400   546890   -10          1

In [46]:
studentVle.nunique()

code_module              7
code_presentation        4
id_student           26074
id_site               6268
date                   295
sum_click              498
dtype: int64

In [47]:
studentVle.isnull().sum()

code_module          0
code_presentation    0
id_student           0
id_site              0
date                 0
sum_click            0
dtype: int64

In [48]:
compareCols(studentassess, studentVle)

Shared columns :  {'id_student'} 

Check if values are present in both dataframes:
True     173835
False        77
Name: id_student, dtype: int64 



In [49]:
compareCols(studentInfo, studentVle)

Shared columns :  {'id_student', 'code_module', 'code_presentation'} 

Check if values are present in both dataframes:
True     29741
False     2852
Name: id_student, dtype: int64 

Check if values are present in both dataframes:
True    32593
Name: code_module, dtype: int64 

Check if values are present in both dataframes:
True    32593
Name: code_presentation, dtype: int64 



Terdapat 2852 student yang ada pada student info namun tidak ada pada student_vle.

In [50]:
studVle_not_in_Info = printDiffValues(studentInfo, studentVle, 'id_student')
studVle_not_in_Info.head(10)

code_module code_presentation  id_student gender                region  \
125         AAA             2013J      292923      F     South East Region   
198         AAA             2013J      405961      M              Scotland   
299         AAA             2013J     2324976      F              Scotland   
307         AAA             2013J     2365101      M     South East Region   
512         AAA             2014J      323805      F  West Midlands Region   
514         AAA             2014J      328734      F   East Anglian Region   
595         AAA             2014J      488382      F         London Region   
609         AAA             2014J      567922      F  North Western Region   
621         AAA             2014J      623710      F     South East Region   
649         AAA             2014J     1469279      F   East Anglian Region   

         highest_education imd_band age_band  num_of_prev_attempts  \
125  A Level or Equivalent  90-100%    35-55                     0   
198  A Level or Equivalent  90-100%     0-35                     0   
299       HE Qualification  90-100%    35-55                     0   
307       HE Qualification   20-30%     0-35                     0   
512  A Level or Equivalent   20-30%     0-35                     0   
514  A Level or Equivalent   80-90%     0-35                     0   
595  A Level or Equivalent    10-20     0-35                     0   
609  A Level or Equivalent   50-60%     0-35                     0   
621  A Level or Equivalent   20-30%    35-55                     0   
649       HE Qualification   40-50%    35-55                     0   

     studied_credits disability final_result imd_band_Categorize  
125              180          N    Withdrawn      Least Deprived  
198              240          Y    Withdrawn      Least Deprived  
299               60          N    Withdrawn      Least Deprived  
307              300          N    Withdrawn       Most Deprived  
512              180          N    Withdrawn       Most Deprived  
514              180          N    Withdrawn      Least Deprived  
595              180          N    Withdrawn       Most Deprived  
609              120          N    Withdrawn     Medium Deprived  
621              120          N    Withdrawn       Most Deprived  
649              120          N    Withdrawn     Medium Deprived

In [51]:
column = studVle_not_in_Info['final_result']

unique, counts = np.unique(column, return_counts = True)

dict(zip(unique, counts))

{'Fail': 333, 'Pass': 3, 'Withdrawn': 2516}

Melalui output serta tabel diatas maka dapat dilihat bahwa terdapat 2516 student yang withdrawn sehingga student tidak mengakses VLE yang ada. 

In [52]:
vle['id_site'] = '_' + vle['id_site'].astype("string")


In [53]:
vle.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6364 entries, 0 to 6363
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   id_site            6364 non-null   string
 1   code_module        6364 non-null   object
 2   code_presentation  6364 non-null   object
 3   activity_type      6364 non-null   object
dtypes: object(3), string(1)
memory usage: 199.0+ KB


In [54]:
studentVle['id_site'] = '_'+ studentVle['id_site'].astype("string")
studentVle['id_student'] = '_'+studentVle['id_student'].astype("string")

In [55]:
studentVle.head()

code_module code_presentation id_student  id_site  date  sum_click
0         AAA             2013J     _28400  _546652   -10          4
1         AAA             2013J     _28400  _546652   -10          1
2         AAA             2013J     _28400  _546652   -10          1
3         AAA             2013J     _28400  _546614   -10         11
4         AAA             2013J     _28400  _546714   -10          1

In [56]:
studentInfo['id_student'] = '_'+ studentInfo['id_student'].astype("string")
studentInfo.head()

code_module code_presentation id_student gender                region  \
0         AAA             2013J     _11391      M   East Anglian Region   
1         AAA             2013J     _28400      F              Scotland   
2         AAA             2013J     _30268      F  North Western Region   
3         AAA             2013J     _31604      F     South East Region   
4         AAA             2013J     _32885      F  West Midlands Region   

       highest_education imd_band age_band  num_of_prev_attempts  \
0       HE Qualification  90-100%     55<=                     0   
1       HE Qualification   20-30%    35-55                     0   
2  A Level or Equivalent   30-40%    35-55                     0   
3  A Level or Equivalent   50-60%    35-55                     0   
4     Lower Than A Level   50-60%     0-35                     0   

   studied_credits disability final_result imd_band_Categorize  
0              240          N         Pass      Least Deprived  
1               60          N         Pass       Most Deprived  
2               60          Y    Withdrawn     Medium Deprived  
3               60          N         Pass     Medium Deprived  
4               60          N         Pass     Medium Deprived

In [57]:
assess['id_assessment'] = '_'+ assess['id_assessment'].astype("string")

In [58]:
assess.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206 entries, 0 to 205
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   code_module        206 non-null    object 
 1   code_presentation  206 non-null    object 
 2   id_assessment      206 non-null    string 
 3   assessment_type    206 non-null    object 
 4   date               195 non-null    float64
 5   weight             206 non-null    float64
dtypes: float64(2), object(3), string(1)
memory usage: 9.8+ KB


In [59]:
studentassess['id_student'] = '_'+ studentassess['id_student'].astype("string")
studentassess['id_assessment'] = '_'+ studentassess['id_assessment'].astype("string")
studentassess.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173912 entries, 0 to 173911
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   id_assessment   173912 non-null  string 
 1   id_student      173912 non-null  string 
 2   date_submitted  173912 non-null  int64  
 3   is_banked       173912 non-null  int64  
 4   score           173912 non-null  float64
dtypes: float64(1), int64(2), string(2)
memory usage: 6.6 MB


## Make Cube and Visualize Insight

In [60]:
session = tt.Session()

In [61]:
studentVleS =session.read_pandas(studentVle, table_name='Studentvle')

In [62]:
studentInfoS =session.read_pandas(studentInfo, table_name='Studentinfo')

In [63]:
studentassessS =session.read_pandas(studentassess, table_name='Studentassess')

In [64]:
cube = session.create_cube(studentVleS)
cube1 = session.create_cube(studentInfoS)
cube2 = session.create_cube(studentassessS)

In [65]:
studentassessS.join(studentInfoS, mapping={'id_student': 'id_student'})

In [66]:
studentVleS.join(studentInfoS, mapping={'id_student': 'id_student'})

In [67]:
hrcubes = cube.hierarchies
hrcubes

Hierarchies(_create_hierarchy_from_arguments=<bound method Cube._create_hierarchy_from_arguments of Cube(_name='Studentvle', _hierarchies=..., _measures=Measures())>, _cube_name='Studentvle')

### Jumlah student dilihat berdasarkan final_result, imd_band, dan highest_education

In [68]:
session.visualize()

Open the notebook in JupyterLab with the atoti extension enabled to build this widget.

### Melihat grafik jumlah student berdasarkan final result, imd_band

In [69]:
session.visualize()

Open the notebook in JupyterLab with the atoti extension enabled to build this widget.

In [70]:
session.visualize()

Open the notebook in JupyterLab with the atoti extension enabled to build this widget.

In [71]:
session.visualize()

Open the notebook in JupyterLab with the atoti extension enabled to build this widget.

### Melihat grafik jumlah student berdasarkan final result, highest_education

In [72]:
session.visualize()

Open the notebook in JupyterLab with the atoti extension enabled to build this widget.

In [73]:
session.visualize()

Open the notebook in JupyterLab with the atoti extension enabled to build this widget.

### Grafik jumlah student berdasarkan imd_band, final_result, dan highest education

In [74]:
session.visualize()

Open the notebook in JupyterLab with the atoti extension enabled to build this widget.

### Melihat apakah rata rata click student dan imd_band berkontribusi terhadap final_result

In [75]:
session.visualize()

Open the notebook in JupyterLab with the atoti extension enabled to build this widget.

In [76]:
session.visualize()

Open the notebook in JupyterLab with the atoti extension enabled to build this widget.

### Melihat hubungan hubungan rerata score, imd_band dengan hasil akhir

In [77]:
session.visualize()

Open the notebook in JupyterLab with the atoti extension enabled to build this widget.

In [78]:
session.visualize()

Open the notebook in JupyterLab with the atoti extension enabled to build this widget.

### Melihat hubungan imd_band dengan rata rata skor

In [79]:
session.visualize()

Open the notebook in JupyterLab with the atoti extension enabled to build this widget.

In [80]:
session.visualize()

Open the notebook in JupyterLab with the atoti extension enabled to build this widget.